googleAnalytics = "UA-15641392-3"

[menu]
  [[menu.main]]
    identifier = "diseno"
    name = "Diseño"
    pre = "Ver los proyectos e historias con clientes"
  	url = "/diseno/"
  	weight = 1

  [[menu.main]]
    identifier = "informacion"
    name = "Información"
    pre = "Toda la información sobre el estudio"
  	url = "/informacion/"
  	weight = 2

  [[menu.main]]
    identifier = "notas"
    name = "Notas"
    pre = "Notas, textos y cosas que se me ocurren"
  	url = "/notas/"
  	weight = 3

  [[menu.main]]
    identifier = "entretiempo"
    name = "Entretiempo"
    pre = "Mi newsletter personal, cosas variadas"
  	url = "/entretiempo/"
  	weight = 4
