[menu]
  [[menu.main]]
    identifier = "diseno"
    name = "Diseño"
    pre = "Historias y proyectos"
  	url = "/diseno/"
  	weight = 1

  [[menu.main]]
    identifier = "informacion"
    name = "Información"
    pre = "Conoce mi estudio"
  	url = "/informacion/"
  	weight = 2

  [[menu.main]]
    identifier = "notas"
    name = "Notas"
    pre = "Pensamientos sobre mi trabajo"
  	url = "/notas/"
  	weight = 3

