baseURL = "https://www.ricardofelix.es/"
languageCode = "es-ES"
title = "Ricardo Félix"
theme = "mustard"

[params]
  subtitle = "Diseño de productos digitales."
  author = "Ricardo Félix"

[permalinks]
  notas = "/:section/:slug"
  diseno = "/:section/:slug"

[markup.goldmark.renderer]
  unsafe = true

[markup.goldmark.parser]
  attribute = true
  autoHeadingID = true
  autoHeadingIDType = "github"

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5
