baseURL = "https://www.ricardofelix.es/"
languageCode = "es-ES"
title = "Ricardo Félix"
theme = "mustard"
googleAnalytics = "UA-15641392-3"

[params]
  subtitle = "Diseño de productos digitales."
  author = "Ricardo Félix"

[permalinks]
  notas = "/:section/:slug"
  diseno = "/:section/:slug"

[markup.goldmark.renderer]
  unsafe = true