baseURL = "https://www.ricardofelix.es/"
languageCode = "es-ES"
title = "Ricardo Félix"
theme = "mustard"

[params]
  description = "Diseño de productos y experiencias digitales."
  author = "Ricardo Félix"

[permalinks]
  notas = "/:section/:slug"
  diseno = "/:section/:slug"

[markup.goldmark.renderer]
  unsafe = true

[markup.goldmark.parser]
  attribute = true
  autoHeadingID = true
  autoHeadingIDType = "github"

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[menu]
  [[menu.main]]
    identifier = "diseno"
    name = "Diseño"
    pre = "Historias y proyectos"
  	url = "/diseno/"
  	weight = 1

  [[menu.main]]
    identifier = "informacion"
    name = "Información"
    pre = "Conoce mi trabajo"
  	url = "/informacion/"
  	weight = 2

  [[menu.main]]
    identifier = "notas"
    name = "Notas"
    pre = "Apuntes sobre diseño"
  	url = "/notas/"
  	weight = 3

  [[menu.main]]
    identifier = "entretiempo"
    name = "Entretiempo"
    pre = "Mi newsletter de cosas"
  	url = "/entretiempo/"
  	weight = 4