baseURL = "https://www.ricardofelix.es/"
languageCode = "es-ES"
title = "Ricardo Félix"
theme = "mustard"
googleAnalytics = "UA-15641392-3"

[params]
  subtitle = "Diseño digital, identidad y front-end."
  author = "Ricardo Félix"
